### ISSUE TITLE
Switch to log::{debug, info, warn, error} instead of println

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/minira#3]
This would allow better filtering of the log output, through selecting precise files via the RUST_LOG environment variable.

**Comment by julian-seward1** [comment]
I think this is mostly, or even completely done now.  @bnjbvr, are the changes I committed earlier this afternoon, what you needed?

**Comment by bnjbvr** [comment]
Yes! Remaining uses of "println" are in tests, and i expect these to be moved over to bin/ any time soon, so we're done here, thank you.
